---
- hosts: all

  vars_files:
    - vars.yml

  roles:
    - server
    - php
    #- apache
    #- mysql
    #- tm
    #- java
    #- tests

  tasks:
    - name: Start Apache, MySQL and PHP
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - php7.1-fpm