---
- name: Add php ondrej repository
  apt_repository:
    repo='ppa:ondrej/php'
    update_cache=yes

- name: Add Microsoft apt repository key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Microsoft apt repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main
    state: present
    update_cache: yes

- name: Install PHP, and other dependencies
  apt: "name={{ item }} state=present"
  with_items:
    - php{{php.version}}-fpm
    - php{{php.version}}-common
    - php{{php.version}}-cli
    - php{{php.version}}-mysql
    - php{{php.version}}-curl
    - php{{php.version}}-readline
    - php{{php.version}}-intl
    - php{{php.version}}-bcmath
    - php{{php.version}}-ldap
    - php{{php.version}}-mbstring
    - php{{php.version}}-gd
    - php{{php.version}}-xml
    - php{{php.version}}-zip
    - php{{php.version}}-opcache
    - php{{php.version}}-json
    - php{{php.version}}-mcrypt
    - php{{php.version}}-dev
    - php-pear

#- name: Install Microsoft prerequisites
#  command: "sudo ACCEPT_EULA=Y apt-get install msodbcsql mssql-tools"

- name: Install Microsoft prerequisites
  apt: "name={{ item }} state=present"
  with_items:
    - unixodbc-dev

#- name: Configure Pear
#  command: pear config-set php_ini `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"` system

- name: Install sqlsrv via pecl
  pear:
    name: pecl/sqlsrv
    state: present

- name: Install pdo_sqlsrv via pecl
  pear:
    name: pecl/pdo_sqlsrv
    state: present

- name: Remove PHP7.1-FPM pool configuration file
  file:
    path: "/etc/php/{{php.version}}/fpm/pool.d/www.conf"
    state: absent

- name: Update PHP7.1-FPM pool configuration file
  template:
    src: "templates/www.conf"
    dest: "/etc/php/{{php.version}}/fpm/pool.d/"
    force: no
  notify: restart php7.1-fpm

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: Run Composer installer.
  command: >
    php composer-installer.php
    chdir=/tmp
    creates=/usr/local/bin/composer

- name: Move Composer into globally-accessible location.
  shell: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer